# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ePills' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UI
  #pod 'SVProgressHUD'
  pod 'FSCalendar'
  
  # Pod for persistence
   pod 'RealmSwift', '3.17.3'
  
  # Pods for resources
  pod 'R.swift'#, '~> 5.0.3'
  
  # Pods for removing technical debt
  pod 'SwiftLint'

  # Pods for Networking
  #pod 'Alamofire', '~> 4.8.2'
  
  # Pods for Analytics
  pod 'Firebase/Analytics'
  
  # Pods for tracking crashes in prod
pod 'Firebase/Crashlytics'
  
  pod 'FLEX', :configuration => :debug

  target 'ePillsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
